# Generated by Django 6.0 on 2025-12-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp_vendor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbankdetail',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendorcontact',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendordocument',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendormanager',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendortag',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='gst_taxpayer_type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='is_msme_registered',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='ledger_group',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_type',
        ),
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='VendorBankDetail',
        ),
        migrations.DeleteModel(
            name='VendorContact',
        ),
        migrations.DeleteModel(
            name='VendorDocument',
        ),
        migrations.DeleteModel(
            name='VendorManager',
        ),
        migrations.DeleteModel(
            name='VendorTag',
        ),
    ]
